// Marcas y modelos habitualmente comercializados (0km y usados) en Argentina.
export const CATALOGO_ARG = {
  "Toyota": ["Corolla", "Corolla Cross", "Etios", "Yaris", "Hilux", "SW4", "RAV4", "Camry", "Prius"],
  "Volkswagen": ["Gol", "Voyage", "Polo", "Virtus", "Vento", "Suran", "Amarok", "Taos", "Nivus", "Fox", "Up!", "Saveiro"],
  "Chevrolet": ["Corsa", "Classic", "Celta", "Onix", "Onix Plus", "Prisma", "Cruze", "Tracker", "S10", "Spin", "Agile", "Astra"],
  "Ford": ["Fiesta", "Focus", "Ka", "EcoSport", "Ranger", "Territory", "Mondeo", "Escort", "F-100"],
  "Fiat": ["Palio", "Siena", "Uno", "Punto", "Cronos", "Argo", "Mobi", "Toro", "Strada", "Idea", "Pulse", "Fiorino"],
  "Renault": ["Clio", "Sandero", "Logan", "Duster", "Kangoo", "Fluence", "Megane", "Captur", "Symbol", "Kwid", "Alaskan", "Oroch", "Stepway"],
  "Peugeot": ["208", "207", "206", "307", "308", "2008", "3008", "Partner", "408", "508"],
  "Citroën": ["C3", "C4 Cactus", "C4 Lounge", "Berlingo", "C4 Aircross", "Xsara", "C3 Aircross"],
  "Honda": ["Civic", "Fit", "HR-V", "City", "CR-V"],
  "Nissan": ["March", "Versa", "Sentra", "Kicks", "Frontier", "X-Trail"],
  "Hyundai": ["HB20", "Creta", "Tucson", "i10", "Accent", "Elantra", "Santa Fe"],
  "Kia": ["Rio", "Sportage", "Cerato", "Picanto", "Sorento", "Soul"],
  "Jeep": ["Renegade", "Compass", "Cherokee", "Grand Cherokee"],
  "RAM": ["1500", "700", "2500"],
  "Chery": ["Tiggo 2", "Tiggo 3", "Tiggo 7", "Tiggo 8", "Arauca", "QQ"],
  "DS": ["DS3", "DS4", "DS7"],
  "Suzuki": ["Fun", "Swift", "Ertiga", "Vitara"],
  "Mitsubishi": ["Lancer", "Outlander", "L200", "ASX"],
  "Subaru": ["Impreza", "Forester", "XV"],
  "Alfa Romeo": ["147", "Giulietta", "Stelvio"],
  "Audi": ["A3", "A4", "Q3", "Q5"],
  "BMW": ["Serie 1", "Serie 3", "X1", "X3"],
  "Mercedes-Benz": ["Clase A", "Clase C", "GLA", "Sprinter", "Vito"],
  "Volvo": ["XC40", "XC60", "S60"],
  "Land Rover": ["Discovery", "Range Rover Evoque", "Defender"],
  "Baic": ["X35", "X55"],
  "JAC": ["S2", "T40", "T60"],
  "Haval": ["H6", "Jolion"],
  "Daihatsu": ["Applause", "Terios"],
  "Isuzu": ["D-Max"],
};

export const MARCAS_ORDENADAS = Object.keys(CATALOGO_ARG).sort((a, b) => a.localeCompare(b, "es"));
